version: "3.9"

services:
  db:
    restart: always
    image: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - 5099:5432
    env_file:
      - ./.env

  backup:
    restart: always
    build:
      context: .
      args:
        PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/logs:/logs
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  data-postgres:
