version: "3.9"

services:
  db:
    restart: always
    image: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backup:
    restart: always
    build:
      # context: https://github.com/lukaszwozny/remote-backup.git
      context: .
      args:
        PGPASSWORD: ${POSTGRES_PASSWORD}
        CRON_SCHEDULE: ${CRON_SCHEDULE}
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/backups:/app/backups
      - ./volumes/media:/app/volumes/media
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  data-postgres:
